#!/usr/bin/env bash

	#montage "*pdf" png:- | convert - sixel:- #but keeping vectors via ghostscript
	#or like cat *pdf | convert - sixel:- but for all pdf:
	gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -g2048x2048 -dPDFFitPage -sOutputFile=- *.pdf \
	| convert - sixel:- #convert to sixel to display inside terminal
	
	#pdftk full-pdf.pdf cat 12-15 output outfile_p12-15.pdf

