#!/bin/sh

missing=""
for cmd in pdfgrep magick qpdf gs; do
    command -v "$cmd" >/dev/null 2>&1 || missing="$missing $cmd"
done
[ -n "$missing" ] && { echo "Missing packages:$missing"; exit 1; }

show_result_numbers=true
[ "$1" = "--no-result-numbers" ] && show_result_numbers=false && shift
[ -z "$1" ] && { echo "Usage: ./pdfgrepSIXEL [--no-result-numbers] 'String'"; exit 1; }

IFS=" " # delimiter
# results in syntax: pdfname.pdf:pagenumber:searchstring
resultslist=$(pdfgrep -n -H -o "$1" *.pdf)
resultscount=$(echo "$resultslist" | cut -d ':' -f 1 | uniq -c | awk '{print $1}') # results per pdf
deduplicatedlist=$(echo "$resultslist" | awk '!a[$0]++') # deduplicate
pageslist=$(echo "$deduplicatedlist" | cut -d ':' -f 2) # page numbers
resultpages=$(echo "$deduplicatedlist" | cut -d ':' -f 1 | uniq -c | awk '{print $1}') # result pages per pdf

# determine individual pdf files:
uniquepdfnames=$(echo "$deduplicatedlist" | cut -d ':' -f 1 | sort -u)
unset IFS
uniquepdfcount=$(echo "$uniquepdfnames" | wc -w)
echo "Found $(echo "$resultslist" | wc -w) results inside $uniquepdfcount pdf files"
echo "(Results per pdf: $resultscount)"

i=1 # number of file
field=1 # position in pagelist
while [ "$i" -le "$uniquepdfcount" ]; do # less or equals

    # different pdf files:
    resultsthispdf=$(echo $resultpages | awk -v N="$i" '{print $N}') # better than loop with ${resultpages:2:1}

    currentpages=$(echo $pageslist | cut -d " " -f "$field"-$(($field + $resultsthispdf - 1)))
    field=$(($field + $resultsthispdf))

    pdfsites="$pdfsites$currentpages"
    [ "$i" -ne "$uniquepdfcount" ] && pdfsites="$pdfsites; "

    # different pdf files end
    i=$((i + 1))
done

echo "$uniquepdfnames"
pagecount=$(echo "$pageslist" | wc -w)
echo "Pages: $pagecount ($pdfsites)"
echo "[Pages per pdf: $resultpages]"

i=1
c=1
current_pdf="$(echo $uniquepdfnames | cut -d " " -f"$c")"
magick -background red -fill white -pointsize 16 label:"$current_pdf" sixel:-
while [ "$i" -le "$pagecount" ]; do
    PGN=$(mktemp)
    
    current_page="$(echo "$pdfsites" | cut -d " " -f"$i" | tr -d ";")"

    # Draw green rectangle with page number
    magick -size 200x200 xc:none -fill green -draw 'rectangle 0,180,30,200' -fill none -pointsize 16 -draw "text 2,196 '$current_page'" pdf:"$PGN"

    # Draw orange rectangle per page including corresponding text search result number unless --no-result-numbers is passed
    [ "$show_result_numbers" = true ] && {
        results_this_page=$(echo "$resultslist" | grep "^$current_pdf:$current_page:" | wc -l)
        magick "$PGN" -fill orange -draw 'rectangle 40,180,70,200' -fill none -pointsize 16 -draw "text 42,196 '$results_this_page'" pdf:"$PGN"
    }

    qpdf --empty --pages "$current_pdf" "$current_page" -- - \
    | gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -g2048x2048 -dPDFFitPage -sOutputFile=- - 2>/dev/null | composite "$PGN" - pdf:- | convert -alpha remove - sixel:- 2>/dev/null

    [ "$(echo "$pdfsites" | cut -d " " -f"$i")" != "$current_page" ] && {
        c=$((c + 1))
        current_pdf="$(echo $uniquepdfnames | cut -d " " -f"$c")"
        magick -background red -fill white -pointsize 16 label:"$current_pdf" sixel:-
    }
    i=$((i + 1))
done

